server:
  port: 8082
spring:
  application:
    name: inventory_service

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: Sriram@#5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
